# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any
from typing import List


@dataclass
class GeLUConf:
    _target_: str = "text.decoder.mlp.GeLU"


@dataclass
class ReLUConf:
    _target_: str = "text.decoder.mlp.ReLU"


@dataclass
class MLPDecoderConf:
    _target_: str = "text.decoder.mlp.MLPDecoder"
    in_dim: int = MISSING
    out_dim: int = MISSING
    bias: bool = MISSING
    hidden_dims: List[int] = None
    activation: Any = MISSING  # Module
