# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING


@dataclass
class MultiheadSelfAttentionConf:
    _target_: str = "text.representation.attention.MultiheadSelfAttention"
    embed_dim: int = MISSING
    num_heads: int = MISSING
    scaling: float = 0.125
    dropout: float = 0.1
