# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Optional


@dataclass
class RobertaEncoderConf:
    _target_: str = "text.representation.roberta.RobertaEncoder"
    vocab_size: int = MISSING
    embedding_dim: int = MISSING
    num_attention_heads: int = MISSING
    num_encoder_layers: int = MISSING
    output_dropout: float = MISSING
    model_path: Optional[str] = None
